
CREATE TABLE COURSE(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    COURSE_NAME VARCHAR(255) NOT NULL,
    COURSE_CODE VARCHAR(255) NOT NULL,
    COURSE_IMAGE VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)